sudo: required

# Resolve hostnames
addons:
  hosts:
    - db

# Setup services
services:
- postgresql
- docker

# Setup python
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: compile
      script: ./scripts/migrate.sh

    - stage: test
      script: ./scripts/test.sh

    - stage: deploy
      if: branch = master
      script: echo "deploy master!!!"
      if: branch = development
      script: echo "deploy development!!!"
