# Setup python
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

# Setup database
services:
- postgresql
env:
- db=postgres

# Migrate database and run tests
script:
    - python diveguide/manage.py migrate
    - ./jenkins/test.sh
