sudo: required

# Resolve hostnames
addons:
  hosts:
    - db

# Setup services
services:
- postgresql
- docker

# Setup python
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

# Migrate database and run tests
script:
    - ./scripts/migrate.sh
    - ./scripts/test.sh
