# Based on this tutorial https://docs.docker.com/compose/django/#connect-the-database

version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python diveguide/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db