# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_location_metoffice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(default='', max_length=200),
        ),
    ]
