# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_location_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='water',
            field=models.CharField(choices=[('FW', 'Fresh water'), ('SW', 'Salt water')], default='SW', max_length=2),
        ),
    ]
