# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_location_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
