# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_location_contact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_website',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
    ]
