# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20170312_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
