# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
