# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_auto_20170312_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='water',
            new_name='water_type',
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(default='', max_length=10),
        ),
    ]
