# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_auto_20170312_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dive_cost',
            field=models.CharField(blank=True, default='Free', max_length=15),
        ),
        migrations.AddField(
            model_name='location',
            name='medical',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='parking_cost',
            field=models.CharField(blank=True, default='Free', max_length=15),
        ),
        migrations.AddField(
            model_name='location',
            name='water_access',
            field=models.CharField(choices=[('RA', 'Ramp'), ('ST', 'Stairs'), ('LA', 'Ladder'), ('BO', 'Boat')], default='RA', max_length=2),
        ),
    ]
