# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_location_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_website',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
