# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170312_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
