# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20170312_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
