# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20170312_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='metoffice_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
